version: '3.8'
services:
  postgres-db:
    image: postgres:15-alpine
    container_name: progra3-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ABCpassword
      POSTGRES_DB: tree_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo-db:
    image: mongo:7
    container_name: progra3-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
  mongo_data:
