server.port=8080

# Selectores para la parte C
app.storage=mongo
app.tree-strategy=collections

# Configuración de la base de datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/tree_db
spring.datasource.username=postgres
spring.datasource.password=ABCpassword
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Hibernate/JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Inicialización de datos PostgreSQL
spring.sql.init.mode=always

# Configuración de MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/tree_db
